import type { OpenRangePreset } from "./open-range-presets";

export type OpenPositionQuote = {
  wallet: string;
  poolId: string;
  inputMint: string;
  inputKind: "native" | "token";
  inputDecimals: number;
  mintA: string;
  mintB: string;
  symbolA: string | null;
  symbolB: string | null;
  decimalsA: number;
  decimalsB: number;
  feeTierBps: number | null;
  tickSpacing: number;
  tickCurrent: number;
  tickLower: number;
  tickUpper: number;
  priceLower: number;
  priceUpper: number;
  currentPrice: string;
  projectedPrice: string;
  rangePreset: OpenRangePreset;
  rangeSide: "below" | "inside" | "above";
  inRange: boolean;
  narrowRange: boolean;
  rangeWarning: string | null;
  requested: string;
  spendA: string;
  spendB: string;
  minOutA: string;
  minOutB: string;
  liquidity: string;
  amountMaxA: string;
  amountMaxB: string;
  requiredA: string;
  requiredB: string;
  toleranceBps: number;
  dustA: string;
  dustB: string;
  resaleInput: string;
  minimumResaleInput: string;
  roundtripCostInput: string;
  passesFloor: boolean;
  floorBps: number;
  suggestedResaleFloorBps: number;
  maxAmountForFloor: string;
  achievedResaleBps: number | null;
  warning: string;
  maxImpactBps: number;
  slippageBps: number;
  routeTouchesTargetPool: boolean;
  token2022A: boolean;
  token2022B: boolean;
  freezeRiskA: boolean;
  freezeRiskB: boolean;
  freezeRisk: boolean;
  transferFee: boolean;
  paused: boolean;
  frozen: boolean;
  unsupportedExtensions: string[];
  rent: {
    refundableLamports: string;
    nonRefundableLamports: string;
    positionNftLamports: string;
    nftAtaLamports: string;
    personalPositionLamports: string;
    tickArrayLamports: string;
    protocolPositionLamports: string;
    tickArrayInitRequired: boolean;
    protocolPositionInitRequired: boolean;
    tickArrayAccounts: string[];
  };
  networkFeeLamportsEstimate: string;
  requiredSolLamports: string;
  solLamports: string;
  sufficientSol: boolean;
  sufficientInput: boolean;
  warnings: string[];
  slot: number;
  fetchedAt: number;
  expiresAt: number;
};

export type OpenPositionSummary = {
  operation: "open-position";
  simulated: true;
  quote: OpenPositionQuote;
  nftMint: string;
  positionAccount: string;
  nftAta: string;
  poolId: string;
  wallet: string;
  inputMint: string;
  inputKind: "native" | "token";
  tickLower: number;
  tickUpper: number;
  startingBalances: { input: string; a: string; b: string };
  simulatedEndingLiquidity: string;
  simulatedInputSpent: string | null;
  simulatedDustA: string;
  simulatedDustB: string;
  simulatedSolDebitLamports: string;
  maxSolDebitLamports: string;
  feeLamports: number;
  rentLamports: number;
  sizeBytes: number;
  unitsConsumed: number | undefined;
  blockhash: string;
  lastValidBlockHeight: number;
  simulatedAt: number;
  expiresAt: number;
  beam?: {
    included: boolean;
    tipLamports: number;
    tipAddress: string | null;
    skippedReason: "disabled" | "no-tip-address" | "oversize" | null;
  };
};
