import { auditPositionFlows } from "../src/lib/lp-flow-audit";
import fs from "node:fs";
import { observePositionTransaction } from "../src/lib/lp-position-observations";
import { PersonalPositionLayout } from "@raydium-io/raydium-sdk-v2";
const dir = "specs/lp-decision/fixtures/";
const read = (name: string) => JSON.parse(fs.readFileSync(`${dir}${name}.json`, "utf8"));
const selected = read("selected-public-position"), pool = read("raydium-pool").data[0];
const transactions = read("rpc-position-signatures").result.map((item: {signature:string}) => observePositionTransaction(item.signature,read(`rpc-position-tx-${item.signature}`).result,{poolId:selected.poolId,positionId:selected.positionMint,mintA:pool.mintA.address,mintB:pool.mintB.address,decimalsA:pool.mintA.decimals,decimalsB:pool.mintB.decimals}));
const account = read("rpc-public-positions").result.find((item:{pubkey:string}) => item.pubkey===selected.positionAccount);
const snapshot = PersonalPositionLayout.decode(Buffer.from(account.account.data[0],"base64")).liquidity.toString();
const evidence = transactions.map((t: ReturnType<typeof observePositionTransaction>)=>t.evidence);
const tokenChecks=transactions.flatMap((t:ReturnType<typeof observePositionTransaction>)=>[pool.mintA.address,pool.mintB.address].map((mint:string)=>{const expected=t.ledger.filter(e=>e.mint===mint).reduce((n,e)=>n+BigInt(e.amountAtomic)*(["deposit","increase"].includes(e.kind)?1n:-1n),0n);const balances=t.evidence.tokenBalances.filter(b=>b.mint===mint&&b.owner===selected.poolId);const observed=balances.length&&balances.every(b=>b.deltaAtomic!==null)?balances.reduce((n,b)=>n+BigInt(b.deltaAtomic!),0n).toString():null;return {signature:t.evidence.signature,mint,eventDeltaAtomic:expected.toString(),vaultDeltaAtomic:observed,matches:observed===null?null:observed===expected.toString()};}));
const sum = evidence.reduce((value:bigint,event:{liquidityDelta:string}) => value+BigInt(event.liquidityDelta),0n).toString();
const flowAudit=auditPositionFlows(read("rpc-position-signatures").result.map((s:{signature:string})=>({signature:s.signature,tx:read(`rpc-position-tx-${s.signature}`).result})),{poolId:selected.poolId,positionId:selected.positionMint,positionAccount:selected.positionAccount,mintA:pool.mintA.address,mintB:pool.mintB.address,decimalsA:pool.mintA.decimals,decimalsB:pool.mintB.decimals});
fs.writeFileSync(`${dir}public-position-flow-audit.json`,JSON.stringify(flowAudit,null,2));
console.log({flowsVerified:flowAudit.verifiedTransactionCount,totals:flowAudit.totals});
const report = {position:selected,liquiditySnapshot:snapshot,liquidityEventSum:sum,liquidityMatches:sum===snapshot,accountingReconciled:false,tokenChecks,reason:"Scoped liquidity consistency only. Wallet flow attribution, historical valuation, historical reward mints and complete costs remain unclassified.",transactions:evidence};
fs.writeFileSync(`${dir}public-transaction-evidence.json`,JSON.stringify(report,null,2));
console.log({liquiditySnapshot:snapshot,liquidityEventSum:sum,liquidityMatches:sum===snapshot,transactions:transactions.length,rewardPayments:evidence.flatMap((e:{rewardSlots:{amountAtomic:string}[]})=>e.rewardSlots).filter((e:{amountAtomic:string})=>e.amountAtomic!=="0").length});
